### ISSUE TITLE
Training from scratch: 3D Coordinates

### ISSUE THREAD

**Issue by virlyananda** [teamtomo/membrain-seg#33]
Hello,

Thanks for releasing this package, the v10 pre-trained model works great on our tomogram. However, as we try to implement training from scratch based on our own data, I found this error: 
![Screenshot from 2023-08-21 11-32-29](https://github.com/teamtomo/membrain-seg/assets/70969092/f246095b-cff3-49cb-a1cb-84af9ab66ce0)
![Screenshot from 2023-08-21 11-30-27](https://github.com/teamtomo/membrain-seg/assets/70969092/72337d3e-66cc-49a5-b8ce-afd57bb66c60)

I followed the tutorial both from the repository and video, it doesn't seem that I'm missing anything? Tomogram path is based on the pre-processed pixel matching step, and segmentation path is based on the binary output from pre-trained model prediction (segmentation).

When I tried to locate 3D coordinates on IMOD, it works fine. If I'm missing something, could you please point out the possible issue? Thanks.

Best,
Virly

**Comment by LorenzLamm** [comment]
Hi Virly,
Thanks for your feedback on this!
I see that your z-coordinate is 35. Since the size of the extracted patches is (160,160,160), this may be too small of a coordinate. In order to extract patches properly from the tomogram, the coordinates should be at least 80 voxels apart from the tomogram boundaries.

Could this be the issue?

Best,
Lorenz

**Comment by virlyananda** [comment]
Hi Lorenz,

Thanks for your response. That could be it. I relocated the coordinate point further away from the tomogram boundaries and it's working now.

Best Regards,
Virly
